export const MOCKED_DATA = [
  {
    name: 'Fajne wydarzenie',
    description: 'Super fajne wydarzenie',
    date: '2020-02-02',
    time: '12:30',
    photo:
      'https://lastrada.pl/wp-content/uploads/2023/03/tematyczna-impreza-firmowa.jpeg',
  },
  {
    name: 'Inna impreza',
    description: 'Ciekawa impreza z różnymi atrakcjami',
    date: '2020-03-15',
    time: '18:00',
    photo: 'https://example.com/another-event.jpg',
  },
  {
    name: 'Koncert rockowy',
    description: 'Koncert zespołu rockowego z nowymi utworami',
    date: '2020-04-25',
    time: '20:00',
    photo: 'https://example.com/rock-concert.jpg',
  },
  {
    name: 'Wydarzenie numer 4',
    description: 'Opis czwartego wydarzenia',
    date: '2020-05-10',
    time: '15:30',
    photo: 'https://example.com/event-4.jpg',
  },
  {
    name: 'Kolejna okazja',
    description: 'Nowe wydarzenie doświadczalne',
    date: '2020-06-20',
    time: '14:00',
    photo: 'https://example.com/another-occasion.png',
  },
  {
    name: 'Spotkanie kulturalne',
    description: 'Spotkanie z artystami i dyskusje kulturalne',
    date: '2020-07-05',
    time: '17:45',
    photo: 'https://example.com/cultural-meeting.jpg',
  },
  {
    name: 'Impreza na świeżym powietrzu',
    description: 'Plenerowa zabawa z grillem i muzyką',
    date: '2020-08-12',
    time: '19:30',
    photo: 'https://example.com/outdoor-party.jpg',
  },
  {
    name: 'Pokaz sztucznych ogni',
    description: 'Wspaniały pokaz pirotechniczny',
    date: '2020-09-28',
    time: '21:00',
    photo: 'https://example.com/fireworks-show.jpg',
  },
  {
    name: 'Warsztaty kreatywne',
    description: 'Warsztaty malarskie i rękodzielnicze',
    date: '2020-10-15',
    time: '16:30',
    photo: 'https://example.com/creative-workshops.jpg',
  },
  {
    name: 'Wieczór poezji',
    description: 'Wieczór pełen poezji i recytacji',
    date: '2020-11-08',
    time: '19:00',
    photo: 'https://example.com/poetry-evening.jpg',
  },
];
